services:
  hz-pipeline:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/sample-pipeline/target/spring-hazelcast-pipeline-dispatcher-sample-pipeline-1.0.3-SNAPSHOT.jar
        hazelcast.platform.solutions.pipeline.dispatcher.sample.ExamplePipeline
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - clientserver

  clientserver-app:
    image: amazoncorretto:11
    command: >
      java 
        -Dspring.config.location=/opt/project/sample-application/config/clientserver.application.properties
        -Dlogging.level.hazelcast.platform.solutions=WARN
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.0.3-SNAPSHOT.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - clientserver

  embedded-app:
    image: amazoncorretto:11
    command: >
      java -Dspring.config.location=/opt/project/sample-application/config/embedded.application.properties
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.0.3-SNAPSHOT.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - embedded

networks:
  default: {}