services:
  hz-pipeline:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/sample-pipeline/target/spring-hazelcast-pipeline-dispatcher-sample-pipeline-1.0.3-SNAPSHOT.jar
        hazelcast.platform.solutions.pipeline.dispatcher.sample.ExamplePipeline
    volumes:
      - ".:/opt/project"
    networks:
      - default

  clientserver-app:
    image: amazoncorretto:11
    command: >
      java 
        -Dspring.config.location=/opt/project/sample-application/config/clientserver.application.properties
        -Dlogging.level.hazelcast.platform.solutions=WARN
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.0.3-SNAPSHOT.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default

  embedded-app:
    image: amazoncorretto:11
    command: >
      java -Dspring.config.location=/opt/project/sample-application/config/embedded.application.properties
        -jar /opt/project/sample-application/target/spring-hazelcast-pipeline-dispatcher-sample-application-1.0.3-SNAPSHOT.jar
    volumes:
      - ".:/opt/project"
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - embedded

  mc:
    image: hazelcast/management-center:5.2.1
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz-pipeline:5701
    ports:
      - "8888:8080"
    networks:
      - default

  load-routing-config:
    image: amazoncorretto:11
    command: >
      java -cp /opt/project/solution/target/spring-hazelcast-pipeline-dispatcher-1.0.3-SNAPSHOT.jar:/opt/project/solution/target/dependency/*
           hazelcast.platform.solutions.pipeline.dispatcher.RoutingConfigLoader 
           /opt/project/sample-application/config/hazelcast-client.yaml 
           /opt/project/reverse_routing.json
    volumes:
      - ".:/opt/project"
    networks:
      - default
    profiles:
      - disabled

networks:
  default: {}