hazelcast-client:
  cluster-name: dev
  instance-name: myappserver
  properties:
    hazelcast.logging.type: slf4j
  network:
    cluster-members:
      - hz-pipeline:5701
    smart-routing: true
  connection-strategy:
    async-start: false
    reconnect-mode: ON
