hazelcast-client:
  cluster-name: dev
  instance-name: myappserver
  network:
    cluster-members:
      - 127.0.0.1:5701
    smart-routing: true
  connection-strategy:
    async-start: true
    reconnect-mode: ASYNC
